# Generated by Django 4.2.28 on 2026-02-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('ATS_REJECTED', 'ATS Rejected'), ('LEVEL1_PENDING', 'Level 1 (MCQ) Pending'), ('LEVEL1_PASSED', 'Level 1 Passed'), ('LEVEL1_FAILED', 'Level 1 Failed'), ('LEVEL2_PENDING', 'Level 2 (Voice) Pending'), ('LEVEL2_PASSED', 'Level 2 Passed'), ('LEVEL2_FAILED', 'Level 2 Failed'), ('LEVEL3_PENDING', 'Level 3 (HR) Pending'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=30)),
                ('ats_score', models.FloatField(default=0.0)),
                ('mcq_score', models.FloatField(default=0.0)),
                ('voice_fluency_score', models.FloatField(default=0.0)),
                ('voice_confidence_score', models.FloatField(default=0.0)),
                ('hr_feedback', models.TextField(blank=True)),
                ('hr_meet_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
