# Generated by Django 4.2.28 on 2026-03-01 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0003_job_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hr_assignee',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'HR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
