# Generated by Django 4.2.28 on 2026-02-28 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceinterview',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_interview', to='jobs.application'),
        ),
        migrations.AddField(
            model_name='candidatemcqattempt',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_attempt', to='jobs.application'),
        ),
    ]
