# Generated by Django 4.2.28 on 2026-03-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatemcqattempt',
            name='questions_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
