# Generated by Django 4.2.28 on 2026-03-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_candidatemcqattempt_questions_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatemcqattempt',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
