# Generated by Django 4.2.28 on 2026-03-01 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_candidatemcqattempt_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voiceinterview',
            old_name='confidence_score',
            new_name='overall_confidence',
        ),
        migrations.RenameField(
            model_name='voiceinterview',
            old_name='fluency_score',
            new_name='overall_technical_score',
        ),
        migrations.RemoveField(
            model_name='voiceinterview',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='voiceinterview',
            name='transcription',
        ),
        migrations.AddField(
            model_name='voiceinterview',
            name='overall_fluency',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='VoiceQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_text', models.CharField(max_length=500)),
                ('expected_answer', models.TextField(blank=True, null=True)),
                ('is_technical', models.BooleanField(default=False)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='voice_interviews/')),
                ('transcription', models.TextField(blank=True)),
                ('fluency_score', models.FloatField(default=0.0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('technical_score', models.FloatField(default=0.0)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.voiceinterview')),
            ],
            options={
                'ordering': ['question_number'],
            },
        ),
    ]
